version: 2
 
models:
  - name: customer
    description: '{{ doc("customer_description") }}'
    columns:
      - name: customer_id
        description: Primary key of the model
        tests:
          - unique
          - not_null

  - name: product_price_history
    tests:
      - dbt_utils.mutually_exclusive_ranges:
          lower_bound_column: created_at
          upper_bound_column: ended_at
          partition_by: product_id 
          gaps: not_allowed
