version: 2
 
models:
  - name: customer
    description: '{{ doc("customer_description") }}'
    columns:
      - name: customer_id
        description: Primary key of the model
        tests:
          - unique
          - not_null